investigate separate ci and cd (example for npgw-portal UI) (#51)

diff --git a/jenkins/jfile-build-a-version b/jenkins/jfile-build-a-version
--- a/jenkins/jfile-build-a-version
+++ b/jenkins/jfile-build-a-version
@@ -17,7 +17,13 @@ pipeline {
     stages {
         stage('Checkout') {
             steps {
-                git credentialsId: 'github-pat', url: 'https://github.com/NPGW/npgw-services.git', branch: 'main'
+                dir('npgw-services') {
+                    git credentialsId: 'github-pat', url: 'https://github.com/NPGW/npgw-services.git', branch: 'main'
+                }
+
+                dir('npgw-portal') {
+                    git credentialsId: 'github-pat', url: 'https://github.com/NPGW/npgw-portal.git', branch: 'main'
+                }
             }
         }
 
@@ -39,18 +45,86 @@ pipeline {
             }
         }
 
-        stage('Set version to pom.xml') {
+        stage('Trigger portal UI build workflow') {
             steps {
-                script {
-                    sh "sed -i \"s/<revision>.*<\\/revision>/<revision>${env.RELEASE_VERSION}<\\/revision>/g\" ./pom.xml"
+                withCredentials([string(credentialsId: 'GH_TOKEN', variable: 'GH_TOKEN')]) {
+                    script {
+                        sh """
+                          gh workflow run build-draft-release.yml \\
+                            --repo NPGW/npgw-portal \\
+                            --ref main \\
+                            -f version=${env.RELEASE_VERSION}
+                        """
+                    }
                 }
             }
         }
 
-        stage('Maven verify') {
+        stage('Wait for portal UI build') {
+            steps {
+                withCredentials([string(credentialsId: 'GH_TOKEN', variable: 'GH_TOKEN')]) {
+                    script {
+                        def version = env.RELEASE_VERSION
+
+                        timeout(time: 5, unit: 'MINUTES') {
+                            waitUntil {
+                                def raw = sh(
+                                    script: """\
+                                        gh release list \\
+                                            --repo NPGW/npgw-portal \\
+                                            --json tagName
+                                    """.stripIndent(),
+                                    returnStdout: true
+                                ).trim()
+
+                                def releases = readJSON text: raw
+
+                                def rel = releases.find { it.tagName == version }
+                                if (rel) {
+                                    echo "Draft release ${version} is ready!"
+                                    return true
+                                } else {
+                                    sleep time: 10, unit: 'SECONDS'
+                                    return false
+                                }
+                            }
+                        }
+                    }
+                }
+            }
+        }
+
+        stage('Download portal UI build') {
+            steps {
+                withCredentials([string(credentialsId: 'GH_TOKEN', variable: 'GH_TOKEN')]) {
+                    script {
+                        def targetDir = "${WORKSPACE}/npgw-portal"
+                        sh """
+                            gh release download ${env.RELEASE_VERSION} \
+                            --repo NPGW/npgw-portal \
+                            --pattern dist.zip \
+                            --dir ${targetDir} --clobber
+
+                            cd ${targetDir}
+                            if [ ! -f "dist.zip" ]; then
+                                echo "ERROR: Portal UI build file not found in ${targetDir}" >&2
+                                exit 1
+                            fi
+                            mv dist.zip portal-web.zip
+                        """
+                    }
+                }
+            }
+        }
+
+        stage('Build backend (npgw-services)') {
             steps {
                 script {
-                    sh "mvn clean verify"
+                    sh """
+                        cd ./npgw-services
+                        sed -i \"s/<revision>.*<\\/revision>/<revision>${env.RELEASE_VERSION}<\\/revision>/g\" ./pom.xml
+                        mvn clean verify
+                    """
                 }
             }
         }
@@ -65,8 +139,8 @@ pipeline {
                 withCredentials([string(credentialsId: 'localstack-auth-token', variable: 'LOCALSTACK_AUTH_TOKEN')]) {
                     script {
                         sh """
-                            echo LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN} > .env
-                            cd ./tests/docker/docker-compose
+                            echo LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN} > npgw-services/.env
+                            cd ./npgw-services/tests/docker/docker-compose
                             ./run-docker-compose-test.sh
                         """
                     }
