trigger api spec build and upload to s3

diff --git a/jenkins/jfile-build-a-version b/jenkins/jfile-build-a-version
--- a/jenkins/jfile-build-a-version
+++ b/jenkins/jfile-build-a-version
@@ -70,6 +70,11 @@ pipeline {
                                 --repo NPGW/npgw-services \\
                                 --ref main \\
                                 -f version=${env.RELEASE_VERSION}
+
+                            gh workflow run build-draft-release.yml \\
+                                --repo NPGW/npgw-common \\
+                                --ref main \\
+                                -f version=${env.RELEASE_VERSION}
                         """
                     }
                 }
@@ -84,7 +89,7 @@ pipeline {
 
                         timeout(time: 5, unit: 'MINUTES') {
                             parallel(
-                                portal: {
+                                npgw-portal: {
                                     waitUntil {
                                         def raw = sh(
                                             script: "gh release list --repo NPGW/npgw-portal --json tagName",
@@ -100,7 +105,7 @@ pipeline {
                                         }
                                     }
                                 },
-                                services: {
+                                npgw-services: {
                                     waitUntil {
                                         def raw = sh(
                                             script: "gh release list --repo NPGW/npgw-services --json tagName",
@@ -125,6 +130,32 @@ pipeline {
                                             return false
                                         }
                                     }
+                                },
+                                npgw-common: {
+                                    waitUntil {
+                                        def raw = sh(
+                                            script: "gh release list --repo NPGW/npgw-common --json tagName",
+                                            returnStdout: true
+                                        ).trim()
+                                        def found = readJSON(text: raw).any { it.tagName == version }
+                                        if (found) {
+                                            echo "npgw-common draft ${version} is ready!"
+                                            def out = sh(
+                                                script: "gh release view ${env.RELEASE_VERSION} --repo NPGW/npgw-common --json assets --jq '.assets[].name'",
+                                                returnStdout: true
+                                            ).trim()
+                                            def assets = out ? out.split('\\n') : []
+                                            if (assets.size() == 2) {
+                                                return true
+                                            } else {
+                                                sleep time: 10, unit: 'SECONDS'
+                                                return false
+                                            }
+                                        } else {
+                                            sleep time: 10, unit: 'SECONDS'
+                                            return false
+                                        }
+                                    }
                                 }
                             )
                         }
@@ -139,6 +170,7 @@ pipeline {
                     script {
                         def targetPortalDir = "${WORKSPACE}/npgw-portal"
                         def targetBackendDir = "${WORKSPACE}/npgw-services"
+                        def targetApiSpecDir = "${WORKSPACE}/npgw-common/docs"
                         sh """
                             gh release download ${env.RELEASE_VERSION} \
                                 --repo NPGW/npgw-portal \
@@ -159,6 +191,16 @@ pipeline {
 
                             if [ -z "\$(ls ${targetBackendDir}/*.tar 2>/dev/null)" ]; then
                                 echo "ERROR: no .tar builds found in ${targetBackendDir}" >&2
+                                exit 1
+                            fi
+
+                            gh release download ${env.RELEASE_VERSION} \
+                                --repo NPGW/npgw-common \
+                                --pattern '*.yml' \
+                                --dir ${targetApiSpecDir} --clobber
+
+                            if [ -z "\$(ls ${targetApiSpecDir}/*.yml 2>/dev/null)" ]; then
+                                echo "ERROR: no .yml builds found in ${targetApiSpecDir}" >&2
                                 exit 1
                             fi
                         """
@@ -249,7 +291,17 @@ pipeline {
             steps {
                 script {
                     sh """
-                    aws s3 sync ${WORKSPACE}/npgw-portal/portal-web/dist s3://${env.AWS_BUCKET_NAME}/npgw-portal/build_${env.RELEASE_VERSION}
+                    aws s3 sync ${WORKSPACE}/npgw-portal/portal-web/dist s3://${env.AWS_BUCKET_NAME}/npgw-portal/${env.RELEASE_VERSION}
+                    """
+                }
+            }
+        }
+
+        stage('Upload API spec to S3') {
+            steps {
+                script {
+                    sh """
+                    aws s3 sync ${WORKSPACE}/npgw-common/docs s3://${env.AWS_BUCKET_NAME}/npgw-common/docs
                     """
                 }
             }
