investigate separate ci and cd (example for npgw-portal UI)

diff --git a/jenkins/jfile-build-a-version b/jenkins/jfile-build-a-version
--- a/jenkins/jfile-build-a-version
+++ b/jenkins/jfile-build-a-version
@@ -12,12 +12,20 @@ pipeline {
         AWS_ROLE = 'arn:aws:iam::214404897309:role/npgw-jenkins-build-a-version-role'
 
         IMAGE_FILE = '.github/IMAGE_LIST.json'
+
+        GH_PORTAL_UI_REPO = 'NPGW/npgw-portal'
     }
 
     stages {
         stage('Checkout') {
             steps {
-                git credentialsId: 'github-pat', url: 'https://github.com/NPGW/npgw-services.git', branch: 'main'
+                dir('npgw-services') {
+                    git credentialsId: 'github-pat', url: 'https://github.com/NPGW/npgw-services.git', branch: 'feature/new-image-in-list'
+                }
+
+                dir('npgw-portal') {
+                    git credentialsId: 'github-pat', url: 'https://github.com/NPGW/npgw-portal.git', branch: 'feature/dockerize-ui'
+                }
             }
         }
 
@@ -39,18 +47,90 @@ pipeline {
             }
         }
 
-        stage('Set version to pom.xml') {
+        stage('Trigger GitHub Actions Release') {
             steps {
-                script {
-                    sh "sed -i \"s/<revision>.*<\\/revision>/<revision>${env.RELEASE_VERSION}<\\/revision>/g\" ./pom.xml"
+                withCredentials([string(credentialsId: 'GH_TOKEN', variable: 'GH_TOKEN')]) {
+                    script {
+                        def workflow     = 'build-draft-release.yml'
+                        def ref          = 'main'
+                        def version      = env.RELEASE_VERSION
+
+                        sh """
+                          gh workflow run ${workflow} \\
+                            --repo ${env.GH_PORTAL_UI_REPO} \\
+                            --ref ${ref} \\
+                            -f version=${version}
+                        """
+                    }
                 }
             }
         }
 
-        stage('Maven verify') {
+        stage('Get Draft Release') {
+            steps {
+                withCredentials([string(credentialsId: 'GH_TOKEN', variable: 'GH_TOKEN')]) {
+                    script {
+                        def version = env.RELEASE_VERSION
+
+                        timeout(time: 5, unit: 'MINUTES') {
+                            waitUntil {
+                                def raw = sh(
+                                    script: """\
+                                        gh release list \\
+                                            --repo ${env.GH_PORTAL_UI_REPO} \\
+                                            --limit 100 \\
+                                            --json tagName
+                                    """.stripIndent(),
+                                    returnStdout: true
+                                ).trim()
+
+                                def releases = readJSON text: raw
+
+                                def rel = releases.find { it.tagName == version }
+                                if (rel) {
+                                    echo "Draft release ${version} is ready!"
+                                    return true
+                                } else {
+                                    sleep time: 10, unit: 'SECONDS'
+                                    return false
+                                }
+                            }
+                        }
+                    }
+                }
+            }
+        }
+
+        stage('Download UI build from Draft Release') {
+            steps {
+                withCredentials([string(credentialsId: 'GH_TOKEN', variable: 'GH_TOKEN')]) {
+                    script {
+                        def targetDir = "${WORKSPACE}/npgw-portal"
+                        def targetFile = "${GH_PORTAL_UI_ASSET_FILE}"
+                        sh """
+                            gh release download ${env.RELEASE_VERSION} \
+                            --repo ${env.GH_PORTAL_UI_REPO} \
+                            --pattern ${targetFile} \
+                            --dir ${targetDir} --clobber
+
+                            if [ ! -f "${targetDir}/${targetFile}" ]; then
+                                echo "ERROR: ${targetFile} not found in ${targetDir}" >&2
+                                exit 1
+                            fi
+                        """
+                    }
+                }
+            }
+        }
+
+        stage('Build backend (npgw-services)') {
             steps {
                 script {
-                    sh "mvn clean verify"
+                    sh """
+                        cd ./npgw-services
+                        sed -i \"s/<revision>.*<\\/revision>/<revision>${env.RELEASE_VERSION}<\\/revision>/g\" ./pom.xml
+                        mvn clean verify
+                    """
                 }
             }
         }
