final

diff --git a/.github/workflows/build-draft-release.yml b/.github/workflows/build-draft-release.yml
--- a/.github/workflows/build-draft-release.yml
+++ b/.github/workflows/build-draft-release.yml
@@ -1,10 +1,6 @@
 name: Build draft release
 
 on:
-  push:
-    branch:
-      - feature/modified-dr-release
-      - main
   workflow_dispatch:
     inputs:
       version:
@@ -23,10 +19,15 @@ jobs:
 
       - name: Get RELEASE_VERSION
         run: |
+          if [[ -z "${{ github.event.inputs.version }}" ]]; then
+            echo "Error: No version passed"
+            exit 1
+          fi
 
-          RELEASE_VERSION="try"
+          RELEASE_VERSION="${{ github.event.inputs.version }}"
           echo "Release version (name): $RELEASE_VERSION"
           echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
+
 
       - name: Set up Node.js
         uses: actions/setup-node@v3
