build-draft-release.yml

diff --git a/.github/workflows/build-draft-release.yml b/.github/workflows/build-draft-release.yml
--- a/.github/workflows/build-draft-release.yml
+++ b/.github/workflows/build-draft-release.yml
@@ -29,13 +29,12 @@ jobs:
       - name: Get RELEASE_VERSION
         run: |
           if [[ -z "${{ github.event.inputs.version }}" ]]; then
-            RELEASE_VERSION="my_try"
+            echo "Error: No version passed"
+            exit 1
           fi
 
           RELEASE_VERSION="${{ github.event.inputs.version }}"
-          if [[ -z "${{ github.event.inputs.version }}" ]]; then
-            RELEASE_VERSION="my_try"
-          fi
+          RELEASE_VERSION="mytry3"
           echo "Release version (name): $RELEASE_VERSION"
           echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
 
