build-draft-release.yml

diff --git a/.github/workflows/build-draft-release.yml b/.github/workflows/build-draft-release.yml
--- a/.github/workflows/build-draft-release.yml
+++ b/.github/workflows/build-draft-release.yml
@@ -1,10 +1,6 @@
 name: Build draft release
 
 on:
-  push:
-    branches:
-      - 'feature/build-draft-release5'
-      - 'main'
   workflow_dispatch:
     inputs:
       version:
@@ -23,7 +19,12 @@ jobs:
 
       - name: Get RELEASE_VERSION
         run: |
-          RELEASE_VERSION="mytry3"
+          if [[ -z "${{ github.event.inputs.version }}" ]]; then
+            echo "Error: No version passed"
+            exit 1
+          fi
+
+          RELEASE_VERSION="${{ github.event.inputs.version }}"
           echo "Release version (name): $RELEASE_VERSION"
           echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
 
